### ISSUE TITLE
Nesting and indentation

### ISSUE THREAD

**Issue by aubreywullschleger** [AA041310/prj-rev-bwfs-tea-cozy#1]
Great! Nice work with the consistent nesting and indentation in your HTML and CSS.  This consistency helps with the organization and readability of your markup/CSS.

Example:  https://github.com/AA041310/prj-rev-bwfs-tea-cozy/blob/master/tea/index.html#L28-L53

**Comment by AA041310** [comment]
Thank you very much for checking my code!
